/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cscl.appointment.booking.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import cscl.appointment.booking.model.CsclAppointmentTimeSlots;
import cscl.appointment.booking.service.CsclAppointmentTimeSlotsLocalService;
import cscl.appointment.booking.service.persistence.CsclAppointmentTimeSlotsPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the cscl appointment time slots local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link cscl.appointment.booking.service.impl.CsclAppointmentTimeSlotsLocalServiceImpl}.
 * </p>
 *
 * @author @rnab
 * @see cscl.appointment.booking.service.impl.CsclAppointmentTimeSlotsLocalServiceImpl
 * @generated
 */
public abstract class CsclAppointmentTimeSlotsLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, CsclAppointmentTimeSlotsLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>CsclAppointmentTimeSlotsLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>cscl.appointment.booking.service.CsclAppointmentTimeSlotsLocalServiceUtil</code>.
	 */

	/**
	 * Adds the cscl appointment time slots to the database. Also notifies the appropriate model listeners.
	 *
	 * @param csclAppointmentTimeSlots the cscl appointment time slots
	 * @return the cscl appointment time slots that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CsclAppointmentTimeSlots addCsclAppointmentTimeSlots(
		CsclAppointmentTimeSlots csclAppointmentTimeSlots) {

		csclAppointmentTimeSlots.setNew(true);

		return csclAppointmentTimeSlotsPersistence.update(
			csclAppointmentTimeSlots);
	}

	/**
	 * Creates a new cscl appointment time slots with the primary key. Does not add the cscl appointment time slots to the database.
	 *
	 * @param id_ the primary key for the new cscl appointment time slots
	 * @return the new cscl appointment time slots
	 */
	@Override
	@Transactional(enabled = false)
	public CsclAppointmentTimeSlots createCsclAppointmentTimeSlots(long id_) {
		return csclAppointmentTimeSlotsPersistence.create(id_);
	}

	/**
	 * Deletes the cscl appointment time slots with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param id_ the primary key of the cscl appointment time slots
	 * @return the cscl appointment time slots that was removed
	 * @throws PortalException if a cscl appointment time slots with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CsclAppointmentTimeSlots deleteCsclAppointmentTimeSlots(long id_)
		throws PortalException {

		return csclAppointmentTimeSlotsPersistence.remove(id_);
	}

	/**
	 * Deletes the cscl appointment time slots from the database. Also notifies the appropriate model listeners.
	 *
	 * @param csclAppointmentTimeSlots the cscl appointment time slots
	 * @return the cscl appointment time slots that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CsclAppointmentTimeSlots deleteCsclAppointmentTimeSlots(
		CsclAppointmentTimeSlots csclAppointmentTimeSlots) {

		return csclAppointmentTimeSlotsPersistence.remove(
			csclAppointmentTimeSlots);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			CsclAppointmentTimeSlots.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return csclAppointmentTimeSlotsPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>cscl.appointment.booking.model.impl.CsclAppointmentTimeSlotsModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return csclAppointmentTimeSlotsPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>cscl.appointment.booking.model.impl.CsclAppointmentTimeSlotsModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return csclAppointmentTimeSlotsPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return csclAppointmentTimeSlotsPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return csclAppointmentTimeSlotsPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public CsclAppointmentTimeSlots fetchCsclAppointmentTimeSlots(long id_) {
		return csclAppointmentTimeSlotsPersistence.fetchByPrimaryKey(id_);
	}

	/**
	 * Returns the cscl appointment time slots with the primary key.
	 *
	 * @param id_ the primary key of the cscl appointment time slots
	 * @return the cscl appointment time slots
	 * @throws PortalException if a cscl appointment time slots with the primary key could not be found
	 */
	@Override
	public CsclAppointmentTimeSlots getCsclAppointmentTimeSlots(long id_)
		throws PortalException {

		return csclAppointmentTimeSlotsPersistence.findByPrimaryKey(id_);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			csclAppointmentTimeSlotsLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(CsclAppointmentTimeSlots.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("id_");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			csclAppointmentTimeSlotsLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			CsclAppointmentTimeSlots.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("id_");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			csclAppointmentTimeSlotsLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(CsclAppointmentTimeSlots.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("id_");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return csclAppointmentTimeSlotsLocalService.
			deleteCsclAppointmentTimeSlots(
				(CsclAppointmentTimeSlots)persistedModel);
	}

	public BasePersistence<CsclAppointmentTimeSlots> getBasePersistence() {
		return csclAppointmentTimeSlotsPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return csclAppointmentTimeSlotsPersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns a range of all the cscl appointment time slotses.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>cscl.appointment.booking.model.impl.CsclAppointmentTimeSlotsModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of cscl appointment time slotses
	 * @param end the upper bound of the range of cscl appointment time slotses (not inclusive)
	 * @return the range of cscl appointment time slotses
	 */
	@Override
	public List<CsclAppointmentTimeSlots> getCsclAppointmentTimeSlotses(
		int start, int end) {

		return csclAppointmentTimeSlotsPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of cscl appointment time slotses.
	 *
	 * @return the number of cscl appointment time slotses
	 */
	@Override
	public int getCsclAppointmentTimeSlotsesCount() {
		return csclAppointmentTimeSlotsPersistence.countAll();
	}

	/**
	 * Updates the cscl appointment time slots in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param csclAppointmentTimeSlots the cscl appointment time slots
	 * @return the cscl appointment time slots that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CsclAppointmentTimeSlots updateCsclAppointmentTimeSlots(
		CsclAppointmentTimeSlots csclAppointmentTimeSlots) {

		return csclAppointmentTimeSlotsPersistence.update(
			csclAppointmentTimeSlots);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			CsclAppointmentTimeSlotsLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		csclAppointmentTimeSlotsLocalService =
			(CsclAppointmentTimeSlotsLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return CsclAppointmentTimeSlotsLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return CsclAppointmentTimeSlots.class;
	}

	protected String getModelClassName() {
		return CsclAppointmentTimeSlots.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				csclAppointmentTimeSlotsPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected CsclAppointmentTimeSlotsLocalService
		csclAppointmentTimeSlotsLocalService;

	@Reference
	protected CsclAppointmentTimeSlotsPersistence
		csclAppointmentTimeSlotsPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

}