/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cscl.appointment.booking.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CsclAppointeeMaster service. Represents a row in the &quot;cscl_appointee_master&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>cscl.appointment.booking.model.impl.CsclAppointeeMasterModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>cscl.appointment.booking.model.impl.CsclAppointeeMasterImpl</code>.
 * </p>
 *
 * @author @rnab
 * @see CsclAppointeeMaster
 * @generated
 */
@ProviderType
public interface CsclAppointeeMasterModel
	extends BaseModel<CsclAppointeeMaster> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cscl appointee master model instance should use the {@link CsclAppointeeMaster} interface instead.
	 */

	/**
	 * Returns the primary key of this cscl appointee master.
	 *
	 * @return the primary key of this cscl appointee master
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cscl appointee master.
	 *
	 * @param primaryKey the primary key of this cscl appointee master
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_ of this cscl appointee master.
	 *
	 * @return the id_ of this cscl appointee master
	 */
	public long getId_();

	/**
	 * Sets the id_ of this cscl appointee master.
	 *
	 * @param id_ the id_ of this cscl appointee master
	 */
	public void setId_(long id_);

	/**
	 * Returns the name of this cscl appointee master.
	 *
	 * @return the name of this cscl appointee master
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this cscl appointee master.
	 *
	 * @param name the name of this cscl appointee master
	 */
	public void setName(String name);

	/**
	 * Returns the designation of this cscl appointee master.
	 *
	 * @return the designation of this cscl appointee master
	 */
	@AutoEscape
	public String getDesignation();

	/**
	 * Sets the designation of this cscl appointee master.
	 *
	 * @param designation the designation of this cscl appointee master
	 */
	public void setDesignation(String designation);

	/**
	 * Returns the is active of this cscl appointee master.
	 *
	 * @return the is active of this cscl appointee master
	 */
	public Boolean getIsActive();

	/**
	 * Sets the is active of this cscl appointee master.
	 *
	 * @param isActive the is active of this cscl appointee master
	 */
	public void setIsActive(Boolean isActive);

}