/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cscl.appointment.booking.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CsclAppointmentTimeSlots service. Represents a row in the &quot;Cscl_Appointment_TimeSlots&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>cscl.appointment.booking.model.impl.CsclAppointmentTimeSlotsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>cscl.appointment.booking.model.impl.CsclAppointmentTimeSlotsImpl</code>.
 * </p>
 *
 * @author @rnab
 * @see CsclAppointmentTimeSlots
 * @generated
 */
@ProviderType
public interface CsclAppointmentTimeSlotsModel
	extends BaseModel<CsclAppointmentTimeSlots> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cscl appointment time slots model instance should use the {@link CsclAppointmentTimeSlots} interface instead.
	 */

	/**
	 * Returns the primary key of this cscl appointment time slots.
	 *
	 * @return the primary key of this cscl appointment time slots
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cscl appointment time slots.
	 *
	 * @param primaryKey the primary key of this cscl appointment time slots
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_ of this cscl appointment time slots.
	 *
	 * @return the id_ of this cscl appointment time slots
	 */
	public long getId_();

	/**
	 * Sets the id_ of this cscl appointment time slots.
	 *
	 * @param id_ the id_ of this cscl appointment time slots
	 */
	public void setId_(long id_);

	/**
	 * Returns the timeslot of this cscl appointment time slots.
	 *
	 * @return the timeslot of this cscl appointment time slots
	 */
	@AutoEscape
	public String getTimeslot();

	/**
	 * Sets the timeslot of this cscl appointment time slots.
	 *
	 * @param Timeslot the timeslot of this cscl appointment time slots
	 */
	public void setTimeslot(String Timeslot);

}