/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cscl.appointment.booking.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CsclApproverMaster service. Represents a row in the &quot;cscl_approver_master&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>cscl.appointment.booking.model.impl.CsclApproverMasterModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>cscl.appointment.booking.model.impl.CsclApproverMasterImpl</code>.
 * </p>
 *
 * @author @rnab
 * @see CsclApproverMaster
 * @generated
 */
@ProviderType
public interface CsclApproverMasterModel extends BaseModel<CsclApproverMaster> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cscl approver master model instance should use the {@link CsclApproverMaster} interface instead.
	 */

	/**
	 * Returns the primary key of this cscl approver master.
	 *
	 * @return the primary key of this cscl approver master
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cscl approver master.
	 *
	 * @param primaryKey the primary key of this cscl approver master
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_ of this cscl approver master.
	 *
	 * @return the id_ of this cscl approver master
	 */
	public long getId_();

	/**
	 * Sets the id_ of this cscl approver master.
	 *
	 * @param id_ the id_ of this cscl approver master
	 */
	public void setId_(long id_);

	/**
	 * Returns the name of this cscl approver master.
	 *
	 * @return the name of this cscl approver master
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this cscl approver master.
	 *
	 * @param name the name of this cscl approver master
	 */
	public void setName(String name);

	/**
	 * Returns the appointee of this cscl approver master.
	 *
	 * @return the appointee of this cscl approver master
	 */
	@AutoEscape
	public String getAppointee();

	/**
	 * Sets the appointee of this cscl approver master.
	 *
	 * @param appointee the appointee of this cscl approver master
	 */
	public void setAppointee(String appointee);

	/**
	 * Returns the user ID of this cscl approver master.
	 *
	 * @return the user ID of this cscl approver master
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this cscl approver master.
	 *
	 * @param userId the user ID of this cscl approver master
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this cscl approver master.
	 *
	 * @return the user uuid of this cscl approver master
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this cscl approver master.
	 *
	 * @param userUuid the user uuid of this cscl approver master
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the is active of this cscl approver master.
	 *
	 * @return the is active of this cscl approver master
	 */
	public Boolean getIsActive();

	/**
	 * Sets the is active of this cscl approver master.
	 *
	 * @param isActive the is active of this cscl approver master
	 */
	public void setIsActive(Boolean isActive);

}