/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cscl.polls.model.impl;

import com.cscl.polls.model.CsclLocalityMaster;
import com.cscl.polls.model.CsclLocalityMasterModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the CsclLocalityMaster service. Represents a row in the &quot;cscl_locality_master&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>CsclLocalityMasterModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CsclLocalityMasterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CsclLocalityMasterImpl
 * @generated
 */
@ProviderType
public class CsclLocalityMasterModelImpl
	extends BaseModelImpl<CsclLocalityMaster>
	implements CsclLocalityMasterModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cscl locality master model instance should use the <code>CsclLocalityMaster</code> interface instead.
	 */
	public static final String TABLE_NAME = "cscl_locality_master";

	public static final Object[][] TABLE_COLUMNS = {
		{"localityId", Types.BIGINT}, {"name", Types.VARCHAR},
		{"isActive", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("localityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("isActive", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table cscl_locality_master (localityId LONG not null primary key,name VARCHAR(75) null,isActive BOOLEAN)";

	public static final String TABLE_SQL_DROP =
		"drop table cscl_locality_master";

	public static final String ORDER_BY_JPQL =
		" ORDER BY csclLocalityMaster.localityId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY cscl_locality_master.localityId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long ISACTIVE_COLUMN_BITMASK = 1L;

	public static final long LOCALITYID_COLUMN_BITMASK = 2L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public CsclLocalityMasterModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _localityId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLocalityId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _localityId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CsclLocalityMaster.class;
	}

	@Override
	public String getModelClassName() {
		return CsclLocalityMaster.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CsclLocalityMaster, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CsclLocalityMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CsclLocalityMaster, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CsclLocalityMaster)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CsclLocalityMaster, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CsclLocalityMaster, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CsclLocalityMaster)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CsclLocalityMaster, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CsclLocalityMaster, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, CsclLocalityMaster>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			CsclLocalityMaster.class.getClassLoader(), CsclLocalityMaster.class,
			ModelWrapper.class);

		try {
			Constructor<CsclLocalityMaster> constructor =
				(Constructor<CsclLocalityMaster>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<CsclLocalityMaster, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<CsclLocalityMaster, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<CsclLocalityMaster, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<CsclLocalityMaster, Object>>();
		Map<String, BiConsumer<CsclLocalityMaster, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<CsclLocalityMaster, ?>>();

		attributeGetterFunctions.put(
			"localityId", CsclLocalityMaster::getLocalityId);
		attributeSetterBiConsumers.put(
			"localityId",
			(BiConsumer<CsclLocalityMaster, Long>)
				CsclLocalityMaster::setLocalityId);
		attributeGetterFunctions.put("name", CsclLocalityMaster::getName);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<CsclLocalityMaster, String>)
				CsclLocalityMaster::setName);
		attributeGetterFunctions.put(
			"isActive", CsclLocalityMaster::getIsActive);
		attributeSetterBiConsumers.put(
			"isActive",
			(BiConsumer<CsclLocalityMaster, Boolean>)
				CsclLocalityMaster::setIsActive);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getLocalityId() {
		return _localityId;
	}

	@Override
	public void setLocalityId(long localityId) {
		_localityId = localityId;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public Boolean getIsActive() {
		return _isActive;
	}

	@Override
	public void setIsActive(Boolean isActive) {
		_columnBitmask |= ISACTIVE_COLUMN_BITMASK;

		if (!_setOriginalIsActive) {
			_setOriginalIsActive = true;

			_originalIsActive = _isActive;
		}

		_isActive = isActive;
	}

	public Boolean getOriginalIsActive() {
		return _originalIsActive;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, CsclLocalityMaster.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CsclLocalityMaster toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CsclLocalityMaster>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CsclLocalityMasterImpl csclLocalityMasterImpl =
			new CsclLocalityMasterImpl();

		csclLocalityMasterImpl.setLocalityId(getLocalityId());
		csclLocalityMasterImpl.setName(getName());
		csclLocalityMasterImpl.setIsActive(getIsActive());

		csclLocalityMasterImpl.resetOriginalValues();

		return csclLocalityMasterImpl;
	}

	@Override
	public int compareTo(CsclLocalityMaster csclLocalityMaster) {
		long primaryKey = csclLocalityMaster.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CsclLocalityMaster)) {
			return false;
		}

		CsclLocalityMaster csclLocalityMaster = (CsclLocalityMaster)obj;

		long primaryKey = csclLocalityMaster.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		CsclLocalityMasterModelImpl csclLocalityMasterModelImpl = this;

		csclLocalityMasterModelImpl._originalIsActive =
			csclLocalityMasterModelImpl._isActive;

		csclLocalityMasterModelImpl._setOriginalIsActive = false;

		csclLocalityMasterModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CsclLocalityMaster> toCacheModel() {
		CsclLocalityMasterCacheModel csclLocalityMasterCacheModel =
			new CsclLocalityMasterCacheModel();

		csclLocalityMasterCacheModel.localityId = getLocalityId();

		csclLocalityMasterCacheModel.name = getName();

		String name = csclLocalityMasterCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			csclLocalityMasterCacheModel.name = null;
		}

		csclLocalityMasterCacheModel.isActive = getIsActive();

		return csclLocalityMasterCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CsclLocalityMaster, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CsclLocalityMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CsclLocalityMaster, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((CsclLocalityMaster)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CsclLocalityMaster, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CsclLocalityMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CsclLocalityMaster, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((CsclLocalityMaster)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CsclLocalityMaster>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _localityId;
	private String _name;
	private Boolean _isActive;
	private Boolean _originalIsActive;
	private boolean _setOriginalIsActive;
	private long _columnBitmask;
	private CsclLocalityMaster _escapedModel;

}