/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cscl.polls.model.impl;

import com.cscl.polls.model.CsclAgeFilter;
import com.cscl.polls.model.CsclAgeFilterModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the CsclAgeFilter service. Represents a row in the &quot;cscl_age_filter&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>CsclAgeFilterModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CsclAgeFilterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CsclAgeFilterImpl
 * @generated
 */
@ProviderType
public class CsclAgeFilterModelImpl
	extends BaseModelImpl<CsclAgeFilter> implements CsclAgeFilterModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cscl age filter model instance should use the <code>CsclAgeFilter</code> interface instead.
	 */
	public static final String TABLE_NAME = "cscl_age_filter";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.BIGINT}, {"name", Types.VARCHAR},
		{"value", Types.VARCHAR}, {"isActive", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("value", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("isActive", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table cscl_age_filter (id_ LONG not null primary key,name VARCHAR(75) null,value VARCHAR(75) null,isActive BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table cscl_age_filter";

	public static final String ORDER_BY_JPQL =
		" ORDER BY csclAgeFilter.id_ ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY cscl_age_filter.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long ISACTIVE_COLUMN_BITMASK = 1L;

	public static final long ID__COLUMN_BITMASK = 2L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public CsclAgeFilterModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id_;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId_(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id_;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CsclAgeFilter.class;
	}

	@Override
	public String getModelClassName() {
		return CsclAgeFilter.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CsclAgeFilter, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CsclAgeFilter, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CsclAgeFilter, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CsclAgeFilter)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CsclAgeFilter, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CsclAgeFilter, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CsclAgeFilter)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CsclAgeFilter, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CsclAgeFilter, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, CsclAgeFilter>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			CsclAgeFilter.class.getClassLoader(), CsclAgeFilter.class,
			ModelWrapper.class);

		try {
			Constructor<CsclAgeFilter> constructor =
				(Constructor<CsclAgeFilter>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<CsclAgeFilter, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<CsclAgeFilter, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<CsclAgeFilter, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<CsclAgeFilter, Object>>();
		Map<String, BiConsumer<CsclAgeFilter, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<CsclAgeFilter, ?>>();

		attributeGetterFunctions.put("id_", CsclAgeFilter::getId_);
		attributeSetterBiConsumers.put(
			"id_", (BiConsumer<CsclAgeFilter, Long>)CsclAgeFilter::setId_);
		attributeGetterFunctions.put("name", CsclAgeFilter::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<CsclAgeFilter, String>)CsclAgeFilter::setName);
		attributeGetterFunctions.put("value", CsclAgeFilter::getValue);
		attributeSetterBiConsumers.put(
			"value",
			(BiConsumer<CsclAgeFilter, String>)CsclAgeFilter::setValue);
		attributeGetterFunctions.put("isActive", CsclAgeFilter::getIsActive);
		attributeSetterBiConsumers.put(
			"isActive",
			(BiConsumer<CsclAgeFilter, Boolean>)CsclAgeFilter::setIsActive);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getId_() {
		return _id_;
	}

	@Override
	public void setId_(long id_) {
		_id_ = id_;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public String getValue() {
		if (_value == null) {
			return "";
		}
		else {
			return _value;
		}
	}

	@Override
	public void setValue(String value) {
		_value = value;
	}

	@Override
	public Boolean getIsActive() {
		return _isActive;
	}

	@Override
	public void setIsActive(Boolean isActive) {
		_columnBitmask |= ISACTIVE_COLUMN_BITMASK;

		if (!_setOriginalIsActive) {
			_setOriginalIsActive = true;

			_originalIsActive = _isActive;
		}

		_isActive = isActive;
	}

	public Boolean getOriginalIsActive() {
		return _originalIsActive;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, CsclAgeFilter.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CsclAgeFilter toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CsclAgeFilter>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CsclAgeFilterImpl csclAgeFilterImpl = new CsclAgeFilterImpl();

		csclAgeFilterImpl.setId_(getId_());
		csclAgeFilterImpl.setName(getName());
		csclAgeFilterImpl.setValue(getValue());
		csclAgeFilterImpl.setIsActive(getIsActive());

		csclAgeFilterImpl.resetOriginalValues();

		return csclAgeFilterImpl;
	}

	@Override
	public int compareTo(CsclAgeFilter csclAgeFilter) {
		long primaryKey = csclAgeFilter.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CsclAgeFilter)) {
			return false;
		}

		CsclAgeFilter csclAgeFilter = (CsclAgeFilter)obj;

		long primaryKey = csclAgeFilter.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		CsclAgeFilterModelImpl csclAgeFilterModelImpl = this;

		csclAgeFilterModelImpl._originalIsActive =
			csclAgeFilterModelImpl._isActive;

		csclAgeFilterModelImpl._setOriginalIsActive = false;

		csclAgeFilterModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CsclAgeFilter> toCacheModel() {
		CsclAgeFilterCacheModel csclAgeFilterCacheModel =
			new CsclAgeFilterCacheModel();

		csclAgeFilterCacheModel.id_ = getId_();

		csclAgeFilterCacheModel.name = getName();

		String name = csclAgeFilterCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			csclAgeFilterCacheModel.name = null;
		}

		csclAgeFilterCacheModel.value = getValue();

		String value = csclAgeFilterCacheModel.value;

		if ((value != null) && (value.length() == 0)) {
			csclAgeFilterCacheModel.value = null;
		}

		csclAgeFilterCacheModel.isActive = getIsActive();

		return csclAgeFilterCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CsclAgeFilter, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CsclAgeFilter, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CsclAgeFilter, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((CsclAgeFilter)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CsclAgeFilter, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CsclAgeFilter, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CsclAgeFilter, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((CsclAgeFilter)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CsclAgeFilter>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _id_;
	private String _name;
	private String _value;
	private Boolean _isActive;
	private Boolean _originalIsActive;
	private boolean _setOriginalIsActive;
	private long _columnBitmask;
	private CsclAgeFilter _escapedModel;

}