/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cscl.polls.model.impl;

import com.cscl.polls.model.CsclPollsQuestion;
import com.cscl.polls.model.CsclPollsQuestionModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.Validator;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the CsclPollsQuestion service. Represents a row in the &quot;cscl_polls_question&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>CsclPollsQuestionModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CsclPollsQuestionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CsclPollsQuestionImpl
 * @generated
 */
@ProviderType
public class CsclPollsQuestionModelImpl
	extends BaseModelImpl<CsclPollsQuestion> implements CsclPollsQuestionModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cscl polls question model instance should use the <code>CsclPollsQuestion</code> interface instead.
	 */
	public static final String TABLE_NAME = "cscl_polls_question";

	public static final Object[][] TABLE_COLUMNS = {
		{"questionId", Types.BIGINT}, {"title", Types.VARCHAR},
		{"question", Types.VARCHAR}, {"description", Types.VARCHAR},
		{"expirationDate", Types.TIMESTAMP},
		{"lastPublishDate", Types.TIMESTAMP}, {"lastVoteDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("questionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("question", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("expirationDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("lastPublishDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("lastVoteDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table cscl_polls_question (questionId LONG not null primary key,title STRING null,question STRING null,description STRING null,expirationDate DATE null,lastPublishDate DATE null,lastVoteDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table cscl_polls_question";

	public static final String ORDER_BY_JPQL =
		" ORDER BY csclPollsQuestion.questionId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY cscl_polls_question.questionId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public CsclPollsQuestionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _questionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setQuestionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _questionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CsclPollsQuestion.class;
	}

	@Override
	public String getModelClassName() {
		return CsclPollsQuestion.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CsclPollsQuestion, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CsclPollsQuestion, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CsclPollsQuestion, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CsclPollsQuestion)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CsclPollsQuestion, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CsclPollsQuestion, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CsclPollsQuestion)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CsclPollsQuestion, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CsclPollsQuestion, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, CsclPollsQuestion>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			CsclPollsQuestion.class.getClassLoader(), CsclPollsQuestion.class,
			ModelWrapper.class);

		try {
			Constructor<CsclPollsQuestion> constructor =
				(Constructor<CsclPollsQuestion>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<CsclPollsQuestion, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<CsclPollsQuestion, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<CsclPollsQuestion, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<CsclPollsQuestion, Object>>();
		Map<String, BiConsumer<CsclPollsQuestion, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<CsclPollsQuestion, ?>>();

		attributeGetterFunctions.put(
			"questionId", CsclPollsQuestion::getQuestionId);
		attributeSetterBiConsumers.put(
			"questionId",
			(BiConsumer<CsclPollsQuestion, Long>)
				CsclPollsQuestion::setQuestionId);
		attributeGetterFunctions.put("title", CsclPollsQuestion::getTitle);
		attributeSetterBiConsumers.put(
			"title",
			(BiConsumer<CsclPollsQuestion, String>)CsclPollsQuestion::setTitle);
		attributeGetterFunctions.put(
			"question", CsclPollsQuestion::getQuestion);
		attributeSetterBiConsumers.put(
			"question",
			(BiConsumer<CsclPollsQuestion, String>)
				CsclPollsQuestion::setQuestion);
		attributeGetterFunctions.put(
			"description", CsclPollsQuestion::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<CsclPollsQuestion, String>)
				CsclPollsQuestion::setDescription);
		attributeGetterFunctions.put(
			"expirationDate", CsclPollsQuestion::getExpirationDate);
		attributeSetterBiConsumers.put(
			"expirationDate",
			(BiConsumer<CsclPollsQuestion, Date>)
				CsclPollsQuestion::setExpirationDate);
		attributeGetterFunctions.put(
			"lastPublishDate", CsclPollsQuestion::getLastPublishDate);
		attributeSetterBiConsumers.put(
			"lastPublishDate",
			(BiConsumer<CsclPollsQuestion, Date>)
				CsclPollsQuestion::setLastPublishDate);
		attributeGetterFunctions.put(
			"lastVoteDate", CsclPollsQuestion::getLastVoteDate);
		attributeSetterBiConsumers.put(
			"lastVoteDate",
			(BiConsumer<CsclPollsQuestion, Date>)
				CsclPollsQuestion::setLastVoteDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getQuestionId() {
		return _questionId;
	}

	@Override
	public void setQuestionId(long questionId) {
		_questionId = questionId;
	}

	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public String getTitle(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTitle(languageId);
	}

	@Override
	public String getTitle(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTitle(languageId, useDefault);
	}

	@Override
	public String getTitle(String languageId) {
		return LocalizationUtil.getLocalization(getTitle(), languageId);
	}

	@Override
	public String getTitle(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getTitle(), languageId, useDefault);
	}

	@Override
	public String getTitleCurrentLanguageId() {
		return _titleCurrentLanguageId;
	}

	@JSON
	@Override
	public String getTitleCurrentValue() {
		Locale locale = getLocale(_titleCurrentLanguageId);

		return getTitle(locale);
	}

	@Override
	public Map<Locale, String> getTitleMap() {
		return LocalizationUtil.getLocalizationMap(getTitle());
	}

	@Override
	public void setTitle(String title) {
		_title = title;
	}

	@Override
	public void setTitle(String title, Locale locale) {
		setTitle(title, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setTitle(String title, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(title)) {
			setTitle(
				LocalizationUtil.updateLocalization(
					getTitle(), "Title", title, languageId, defaultLanguageId));
		}
		else {
			setTitle(
				LocalizationUtil.removeLocalization(
					getTitle(), "Title", languageId));
		}
	}

	@Override
	public void setTitleCurrentLanguageId(String languageId) {
		_titleCurrentLanguageId = languageId;
	}

	@Override
	public void setTitleMap(Map<Locale, String> titleMap) {
		setTitleMap(titleMap, LocaleUtil.getDefault());
	}

	@Override
	public void setTitleMap(
		Map<Locale, String> titleMap, Locale defaultLocale) {

		if (titleMap == null) {
			return;
		}

		setTitle(
			LocalizationUtil.updateLocalization(
				titleMap, getTitle(), "Title",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public String getQuestion() {
		if (_question == null) {
			return "";
		}
		else {
			return _question;
		}
	}

	@Override
	public String getQuestion(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getQuestion(languageId);
	}

	@Override
	public String getQuestion(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getQuestion(languageId, useDefault);
	}

	@Override
	public String getQuestion(String languageId) {
		return LocalizationUtil.getLocalization(getQuestion(), languageId);
	}

	@Override
	public String getQuestion(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getQuestion(), languageId, useDefault);
	}

	@Override
	public String getQuestionCurrentLanguageId() {
		return _questionCurrentLanguageId;
	}

	@JSON
	@Override
	public String getQuestionCurrentValue() {
		Locale locale = getLocale(_questionCurrentLanguageId);

		return getQuestion(locale);
	}

	@Override
	public Map<Locale, String> getQuestionMap() {
		return LocalizationUtil.getLocalizationMap(getQuestion());
	}

	@Override
	public void setQuestion(String question) {
		_question = question;
	}

	@Override
	public void setQuestion(String question, Locale locale) {
		setQuestion(question, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setQuestion(
		String question, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(question)) {
			setQuestion(
				LocalizationUtil.updateLocalization(
					getQuestion(), "Question", question, languageId,
					defaultLanguageId));
		}
		else {
			setQuestion(
				LocalizationUtil.removeLocalization(
					getQuestion(), "Question", languageId));
		}
	}

	@Override
	public void setQuestionCurrentLanguageId(String languageId) {
		_questionCurrentLanguageId = languageId;
	}

	@Override
	public void setQuestionMap(Map<Locale, String> questionMap) {
		setQuestionMap(questionMap, LocaleUtil.getDefault());
	}

	@Override
	public void setQuestionMap(
		Map<Locale, String> questionMap, Locale defaultLocale) {

		if (questionMap == null) {
			return;
		}

		setQuestion(
			LocalizationUtil.updateLocalization(
				questionMap, getQuestion(), "Question",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public String getDescription(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId);
	}

	@Override
	public String getDescription(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId, useDefault);
	}

	@Override
	public String getDescription(String languageId) {
		return LocalizationUtil.getLocalization(getDescription(), languageId);
	}

	@Override
	public String getDescription(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getDescription(), languageId, useDefault);
	}

	@Override
	public String getDescriptionCurrentLanguageId() {
		return _descriptionCurrentLanguageId;
	}

	@JSON
	@Override
	public String getDescriptionCurrentValue() {
		Locale locale = getLocale(_descriptionCurrentLanguageId);

		return getDescription(locale);
	}

	@Override
	public Map<Locale, String> getDescriptionMap() {
		return LocalizationUtil.getLocalizationMap(getDescription());
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public void setDescription(String description, Locale locale) {
		setDescription(description, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setDescription(
		String description, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(description)) {
			setDescription(
				LocalizationUtil.updateLocalization(
					getDescription(), "Description", description, languageId,
					defaultLanguageId));
		}
		else {
			setDescription(
				LocalizationUtil.removeLocalization(
					getDescription(), "Description", languageId));
		}
	}

	@Override
	public void setDescriptionCurrentLanguageId(String languageId) {
		_descriptionCurrentLanguageId = languageId;
	}

	@Override
	public void setDescriptionMap(Map<Locale, String> descriptionMap) {
		setDescriptionMap(descriptionMap, LocaleUtil.getDefault());
	}

	@Override
	public void setDescriptionMap(
		Map<Locale, String> descriptionMap, Locale defaultLocale) {

		if (descriptionMap == null) {
			return;
		}

		setDescription(
			LocalizationUtil.updateLocalization(
				descriptionMap, getDescription(), "Description",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public Date getExpirationDate() {
		return _expirationDate;
	}

	@Override
	public void setExpirationDate(Date expirationDate) {
		_expirationDate = expirationDate;
	}

	@Override
	public Date getLastPublishDate() {
		return _lastPublishDate;
	}

	@Override
	public void setLastPublishDate(Date lastPublishDate) {
		_lastPublishDate = lastPublishDate;
	}

	@Override
	public Date getLastVoteDate() {
		return _lastVoteDate;
	}

	@Override
	public void setLastVoteDate(Date lastVoteDate) {
		_lastVoteDate = lastVoteDate;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, CsclPollsQuestion.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> titleMap = getTitleMap();

		for (Map.Entry<Locale, String> entry : titleMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> questionMap = getQuestionMap();

		for (Map.Entry<Locale, String> entry : questionMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> descriptionMap = getDescriptionMap();

		for (Map.Entry<Locale, String> entry : descriptionMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getTitle();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			CsclPollsQuestion.class.getName(), getPrimaryKey(), defaultLocale,
			availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String title = getTitle(defaultLocale);

		if (Validator.isNull(title)) {
			setTitle(getTitle(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setTitle(getTitle(defaultLocale), defaultLocale, defaultLocale);
		}

		String question = getQuestion(defaultLocale);

		if (Validator.isNull(question)) {
			setQuestion(getQuestion(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setQuestion(
				getQuestion(defaultLocale), defaultLocale, defaultLocale);
		}

		String description = getDescription(defaultLocale);

		if (Validator.isNull(description)) {
			setDescription(
				getDescription(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setDescription(
				getDescription(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public CsclPollsQuestion toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CsclPollsQuestion>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CsclPollsQuestionImpl csclPollsQuestionImpl =
			new CsclPollsQuestionImpl();

		csclPollsQuestionImpl.setQuestionId(getQuestionId());
		csclPollsQuestionImpl.setTitle(getTitle());
		csclPollsQuestionImpl.setQuestion(getQuestion());
		csclPollsQuestionImpl.setDescription(getDescription());
		csclPollsQuestionImpl.setExpirationDate(getExpirationDate());
		csclPollsQuestionImpl.setLastPublishDate(getLastPublishDate());
		csclPollsQuestionImpl.setLastVoteDate(getLastVoteDate());

		csclPollsQuestionImpl.resetOriginalValues();

		return csclPollsQuestionImpl;
	}

	@Override
	public int compareTo(CsclPollsQuestion csclPollsQuestion) {
		long primaryKey = csclPollsQuestion.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CsclPollsQuestion)) {
			return false;
		}

		CsclPollsQuestion csclPollsQuestion = (CsclPollsQuestion)obj;

		long primaryKey = csclPollsQuestion.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<CsclPollsQuestion> toCacheModel() {
		CsclPollsQuestionCacheModel csclPollsQuestionCacheModel =
			new CsclPollsQuestionCacheModel();

		csclPollsQuestionCacheModel.questionId = getQuestionId();

		csclPollsQuestionCacheModel.title = getTitle();

		String title = csclPollsQuestionCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			csclPollsQuestionCacheModel.title = null;
		}

		csclPollsQuestionCacheModel.question = getQuestion();

		String question = csclPollsQuestionCacheModel.question;

		if ((question != null) && (question.length() == 0)) {
			csclPollsQuestionCacheModel.question = null;
		}

		csclPollsQuestionCacheModel.description = getDescription();

		String description = csclPollsQuestionCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			csclPollsQuestionCacheModel.description = null;
		}

		Date expirationDate = getExpirationDate();

		if (expirationDate != null) {
			csclPollsQuestionCacheModel.expirationDate =
				expirationDate.getTime();
		}
		else {
			csclPollsQuestionCacheModel.expirationDate = Long.MIN_VALUE;
		}

		Date lastPublishDate = getLastPublishDate();

		if (lastPublishDate != null) {
			csclPollsQuestionCacheModel.lastPublishDate =
				lastPublishDate.getTime();
		}
		else {
			csclPollsQuestionCacheModel.lastPublishDate = Long.MIN_VALUE;
		}

		Date lastVoteDate = getLastVoteDate();

		if (lastVoteDate != null) {
			csclPollsQuestionCacheModel.lastVoteDate = lastVoteDate.getTime();
		}
		else {
			csclPollsQuestionCacheModel.lastVoteDate = Long.MIN_VALUE;
		}

		return csclPollsQuestionCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CsclPollsQuestion, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CsclPollsQuestion, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CsclPollsQuestion, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((CsclPollsQuestion)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CsclPollsQuestion, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CsclPollsQuestion, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CsclPollsQuestion, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((CsclPollsQuestion)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CsclPollsQuestion>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _questionId;
	private String _title;
	private String _titleCurrentLanguageId;
	private String _question;
	private String _questionCurrentLanguageId;
	private String _description;
	private String _descriptionCurrentLanguageId;
	private Date _expirationDate;
	private Date _lastPublishDate;
	private Date _lastVoteDate;
	private CsclPollsQuestion _escapedModel;

}