/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cscl.appointment.booking.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import cscl.appointment.booking.model.CsclApproverMaster;
import cscl.appointment.booking.model.CsclApproverMasterModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CsclApproverMaster service. Represents a row in the &quot;cscl_approver_master&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CsclApproverMasterModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CsclApproverMasterImpl}.
 * </p>
 *
 * @author @rnab
 * @see CsclApproverMasterImpl
 * @generated
 */
public class CsclApproverMasterModelImpl
	extends BaseModelImpl<CsclApproverMaster>
	implements CsclApproverMasterModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cscl approver master model instance should use the <code>CsclApproverMaster</code> interface instead.
	 */
	public static final String TABLE_NAME = "cscl_approver_master";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.BIGINT}, {"name", Types.VARCHAR},
		{"appointee", Types.VARCHAR}, {"userId", Types.BIGINT},
		{"isActive", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("appointee", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("isActive", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table cscl_approver_master (id_ LONG not null primary key,name VARCHAR(75) null,appointee VARCHAR(75) null,userId LONG,isActive BOOLEAN)";

	public static final String TABLE_SQL_DROP =
		"drop table cscl_approver_master";

	public static final String ORDER_BY_JPQL =
		" ORDER BY csclApproverMaster.id_ ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY cscl_approver_master.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long ISACTIVE_COLUMN_BITMASK = 1L;

	public static final long ID__COLUMN_BITMASK = 2L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public CsclApproverMasterModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id_;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId_(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id_;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CsclApproverMaster.class;
	}

	@Override
	public String getModelClassName() {
		return CsclApproverMaster.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CsclApproverMaster, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CsclApproverMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CsclApproverMaster, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CsclApproverMaster)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CsclApproverMaster, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CsclApproverMaster, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CsclApproverMaster)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CsclApproverMaster, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CsclApproverMaster, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, CsclApproverMaster>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			CsclApproverMaster.class.getClassLoader(), CsclApproverMaster.class,
			ModelWrapper.class);

		try {
			Constructor<CsclApproverMaster> constructor =
				(Constructor<CsclApproverMaster>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<CsclApproverMaster, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<CsclApproverMaster, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<CsclApproverMaster, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<CsclApproverMaster, Object>>();
		Map<String, BiConsumer<CsclApproverMaster, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<CsclApproverMaster, ?>>();

		attributeGetterFunctions.put("id_", CsclApproverMaster::getId_);
		attributeSetterBiConsumers.put(
			"id_",
			(BiConsumer<CsclApproverMaster, Long>)CsclApproverMaster::setId_);
		attributeGetterFunctions.put("name", CsclApproverMaster::getName);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<CsclApproverMaster, String>)
				CsclApproverMaster::setName);
		attributeGetterFunctions.put(
			"appointee", CsclApproverMaster::getAppointee);
		attributeSetterBiConsumers.put(
			"appointee",
			(BiConsumer<CsclApproverMaster, String>)
				CsclApproverMaster::setAppointee);
		attributeGetterFunctions.put("userId", CsclApproverMaster::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<CsclApproverMaster, Long>)
				CsclApproverMaster::setUserId);
		attributeGetterFunctions.put(
			"isActive", CsclApproverMaster::getIsActive);
		attributeSetterBiConsumers.put(
			"isActive",
			(BiConsumer<CsclApproverMaster, Boolean>)
				CsclApproverMaster::setIsActive);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getId_() {
		return _id_;
	}

	@Override
	public void setId_(long id_) {
		_id_ = id_;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public String getAppointee() {
		if (_appointee == null) {
			return "";
		}
		else {
			return _appointee;
		}
	}

	@Override
	public void setAppointee(String appointee) {
		_appointee = appointee;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public Boolean getIsActive() {
		return _isActive;
	}

	@Override
	public void setIsActive(Boolean isActive) {
		_columnBitmask |= ISACTIVE_COLUMN_BITMASK;

		if (!_setOriginalIsActive) {
			_setOriginalIsActive = true;

			_originalIsActive = _isActive;
		}

		_isActive = isActive;
	}

	public Boolean getOriginalIsActive() {
		return _originalIsActive;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, CsclApproverMaster.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CsclApproverMaster toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CsclApproverMaster>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CsclApproverMasterImpl csclApproverMasterImpl =
			new CsclApproverMasterImpl();

		csclApproverMasterImpl.setId_(getId_());
		csclApproverMasterImpl.setName(getName());
		csclApproverMasterImpl.setAppointee(getAppointee());
		csclApproverMasterImpl.setUserId(getUserId());
		csclApproverMasterImpl.setIsActive(getIsActive());

		csclApproverMasterImpl.resetOriginalValues();

		return csclApproverMasterImpl;
	}

	@Override
	public int compareTo(CsclApproverMaster csclApproverMaster) {
		long primaryKey = csclApproverMaster.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CsclApproverMaster)) {
			return false;
		}

		CsclApproverMaster csclApproverMaster = (CsclApproverMaster)obj;

		long primaryKey = csclApproverMaster.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		CsclApproverMasterModelImpl csclApproverMasterModelImpl = this;

		csclApproverMasterModelImpl._originalIsActive =
			csclApproverMasterModelImpl._isActive;

		csclApproverMasterModelImpl._setOriginalIsActive = false;

		csclApproverMasterModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CsclApproverMaster> toCacheModel() {
		CsclApproverMasterCacheModel csclApproverMasterCacheModel =
			new CsclApproverMasterCacheModel();

		csclApproverMasterCacheModel.id_ = getId_();

		csclApproverMasterCacheModel.name = getName();

		String name = csclApproverMasterCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			csclApproverMasterCacheModel.name = null;
		}

		csclApproverMasterCacheModel.appointee = getAppointee();

		String appointee = csclApproverMasterCacheModel.appointee;

		if ((appointee != null) && (appointee.length() == 0)) {
			csclApproverMasterCacheModel.appointee = null;
		}

		csclApproverMasterCacheModel.userId = getUserId();

		csclApproverMasterCacheModel.isActive = getIsActive();

		return csclApproverMasterCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CsclApproverMaster, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CsclApproverMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CsclApproverMaster, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((CsclApproverMaster)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CsclApproverMaster, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CsclApproverMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CsclApproverMaster, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((CsclApproverMaster)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CsclApproverMaster>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _id_;
	private String _name;
	private String _appointee;
	private long _userId;
	private Boolean _isActive;
	private Boolean _originalIsActive;
	private boolean _setOriginalIsActive;
	private long _columnBitmask;
	private CsclApproverMaster _escapedModel;

}