/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cscl.appointment.booking.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;

import cscl.appointment.booking.model.CsclAppointmentTimeSlots;
import cscl.appointment.booking.model.CsclAppointmentTimeSlotsModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CsclAppointmentTimeSlots service. Represents a row in the &quot;Cscl_Appointment_TimeSlots&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CsclAppointmentTimeSlotsModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CsclAppointmentTimeSlotsImpl}.
 * </p>
 *
 * @author @rnab
 * @see CsclAppointmentTimeSlotsImpl
 * @generated
 */
public class CsclAppointmentTimeSlotsModelImpl
	extends BaseModelImpl<CsclAppointmentTimeSlots>
	implements CsclAppointmentTimeSlotsModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cscl appointment time slots model instance should use the <code>CsclAppointmentTimeSlots</code> interface instead.
	 */
	public static final String TABLE_NAME = "Cscl_Appointment_TimeSlots";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.BIGINT}, {"Timeslot", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("Timeslot", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Cscl_Appointment_TimeSlots (id_ LONG not null primary key,Timeslot VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table Cscl_Appointment_TimeSlots";

	public static final String ORDER_BY_JPQL =
		" ORDER BY csclAppointmentTimeSlots.id_ ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Cscl_Appointment_TimeSlots.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public CsclAppointmentTimeSlotsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id_;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId_(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id_;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CsclAppointmentTimeSlots.class;
	}

	@Override
	public String getModelClassName() {
		return CsclAppointmentTimeSlots.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CsclAppointmentTimeSlots, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CsclAppointmentTimeSlots, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CsclAppointmentTimeSlots, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CsclAppointmentTimeSlots)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CsclAppointmentTimeSlots, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CsclAppointmentTimeSlots, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CsclAppointmentTimeSlots)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CsclAppointmentTimeSlots, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CsclAppointmentTimeSlots, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, CsclAppointmentTimeSlots>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			CsclAppointmentTimeSlots.class.getClassLoader(),
			CsclAppointmentTimeSlots.class, ModelWrapper.class);

		try {
			Constructor<CsclAppointmentTimeSlots> constructor =
				(Constructor<CsclAppointmentTimeSlots>)
					proxyClass.getConstructor(InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<CsclAppointmentTimeSlots, Object>>
		_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<CsclAppointmentTimeSlots, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<CsclAppointmentTimeSlots, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<CsclAppointmentTimeSlots, Object>>();
		Map<String, BiConsumer<CsclAppointmentTimeSlots, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<CsclAppointmentTimeSlots, ?>>();

		attributeGetterFunctions.put("id_", CsclAppointmentTimeSlots::getId_);
		attributeSetterBiConsumers.put(
			"id_",
			(BiConsumer<CsclAppointmentTimeSlots, Long>)
				CsclAppointmentTimeSlots::setId_);
		attributeGetterFunctions.put(
			"Timeslot", CsclAppointmentTimeSlots::getTimeslot);
		attributeSetterBiConsumers.put(
			"Timeslot",
			(BiConsumer<CsclAppointmentTimeSlots, String>)
				CsclAppointmentTimeSlots::setTimeslot);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getId_() {
		return _id_;
	}

	@Override
	public void setId_(long id_) {
		_id_ = id_;
	}

	@Override
	public String getTimeslot() {
		if (_Timeslot == null) {
			return "";
		}
		else {
			return _Timeslot;
		}
	}

	@Override
	public void setTimeslot(String Timeslot) {
		_Timeslot = Timeslot;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, CsclAppointmentTimeSlots.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CsclAppointmentTimeSlots toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CsclAppointmentTimeSlots>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CsclAppointmentTimeSlotsImpl csclAppointmentTimeSlotsImpl =
			new CsclAppointmentTimeSlotsImpl();

		csclAppointmentTimeSlotsImpl.setId_(getId_());
		csclAppointmentTimeSlotsImpl.setTimeslot(getTimeslot());

		csclAppointmentTimeSlotsImpl.resetOriginalValues();

		return csclAppointmentTimeSlotsImpl;
	}

	@Override
	public int compareTo(CsclAppointmentTimeSlots csclAppointmentTimeSlots) {
		long primaryKey = csclAppointmentTimeSlots.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CsclAppointmentTimeSlots)) {
			return false;
		}

		CsclAppointmentTimeSlots csclAppointmentTimeSlots =
			(CsclAppointmentTimeSlots)obj;

		long primaryKey = csclAppointmentTimeSlots.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<CsclAppointmentTimeSlots> toCacheModel() {
		CsclAppointmentTimeSlotsCacheModel csclAppointmentTimeSlotsCacheModel =
			new CsclAppointmentTimeSlotsCacheModel();

		csclAppointmentTimeSlotsCacheModel.id_ = getId_();

		csclAppointmentTimeSlotsCacheModel.Timeslot = getTimeslot();

		String Timeslot = csclAppointmentTimeSlotsCacheModel.Timeslot;

		if ((Timeslot != null) && (Timeslot.length() == 0)) {
			csclAppointmentTimeSlotsCacheModel.Timeslot = null;
		}

		return csclAppointmentTimeSlotsCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CsclAppointmentTimeSlots, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CsclAppointmentTimeSlots, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CsclAppointmentTimeSlots, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply((CsclAppointmentTimeSlots)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CsclAppointmentTimeSlots, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CsclAppointmentTimeSlots, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CsclAppointmentTimeSlots, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((CsclAppointmentTimeSlots)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, CsclAppointmentTimeSlots>
				_escapedModelProxyProviderFunction =
					_getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _id_;
	private String _Timeslot;
	private CsclAppointmentTimeSlots _escapedModel;

}