/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cscl.appointment.booking.model.impl;

import cscl.appointment.booking.model.CsclAppointeeMaster;
import cscl.appointment.booking.service.CsclAppointeeMasterLocalServiceUtil;

/**
 * The extended model base implementation for the CsclAppointeeMaster service. Represents a row in the &quot;cscl_appointee_master&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CsclAppointeeMasterImpl}.
 * </p>
 *
 * @author @rnab
 * @see CsclAppointeeMasterImpl
 * @see CsclAppointeeMaster
 * @generated
 */
public abstract class CsclAppointeeMasterBaseImpl
	extends CsclAppointeeMasterModelImpl implements CsclAppointeeMaster {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cscl appointee master model instance should use the <code>CsclAppointeeMaster</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CsclAppointeeMasterLocalServiceUtil.addCsclAppointeeMaster(this);
		}
		else {
			CsclAppointeeMasterLocalServiceUtil.updateCsclAppointeeMaster(this);
		}
	}

}