/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cscl.event.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.LocalizedModel;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CsclEvent service. Represents a row in the &quot;cscl_event&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.cscl.event.model.impl.CsclEventModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.cscl.event.model.impl.CsclEventImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CsclEvent
 * @generated
 */
@ProviderType
public interface CsclEventModel extends BaseModel<CsclEvent>, LocalizedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cscl event model instance should use the {@link CsclEvent} interface instead.
	 */

	/**
	 * Returns the primary key of this cscl event.
	 *
	 * @return the primary key of this cscl event
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cscl event.
	 *
	 * @param primaryKey the primary key of this cscl event
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this cscl event.
	 *
	 * @return the uuid of this cscl event
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this cscl event.
	 *
	 * @param uuid the uuid of this cscl event
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the event ID of this cscl event.
	 *
	 * @return the event ID of this cscl event
	 */
	public long getEventId();

	/**
	 * Sets the event ID of this cscl event.
	 *
	 * @param eventId the event ID of this cscl event
	 */
	public void setEventId(long eventId);

	/**
	 * Returns the created by ID of this cscl event.
	 *
	 * @return the created by ID of this cscl event
	 */
	public long getCreatedById();

	/**
	 * Sets the created by ID of this cscl event.
	 *
	 * @param createdById the created by ID of this cscl event
	 */
	public void setCreatedById(long createdById);

	/**
	 * Returns the updated by ID of this cscl event.
	 *
	 * @return the updated by ID of this cscl event
	 */
	public long getUpdatedById();

	/**
	 * Sets the updated by ID of this cscl event.
	 *
	 * @param updatedById the updated by ID of this cscl event
	 */
	public void setUpdatedById(long updatedById);

	/**
	 * Returns the user name of this cscl event.
	 *
	 * @return the user name of this cscl event
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this cscl event.
	 *
	 * @param userName the user name of this cscl event
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this cscl event.
	 *
	 * @return the create date of this cscl event
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this cscl event.
	 *
	 * @param createDate the create date of this cscl event
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this cscl event.
	 *
	 * @return the modified date of this cscl event
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this cscl event.
	 *
	 * @param modifiedDate the modified date of this cscl event
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the title of this cscl event.
	 *
	 * @return the title of this cscl event
	 */
	public String getTitle();

	/**
	 * Returns the localized title of this cscl event in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized title of this cscl event
	 */
	@AutoEscape
	public String getTitle(Locale locale);

	/**
	 * Returns the localized title of this cscl event in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized title of this cscl event. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getTitle(Locale locale, boolean useDefault);

	/**
	 * Returns the localized title of this cscl event in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized title of this cscl event
	 */
	@AutoEscape
	public String getTitle(String languageId);

	/**
	 * Returns the localized title of this cscl event in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized title of this cscl event
	 */
	@AutoEscape
	public String getTitle(String languageId, boolean useDefault);

	@AutoEscape
	public String getTitleCurrentLanguageId();

	@AutoEscape
	public String getTitleCurrentValue();

	/**
	 * Returns a map of the locales and localized titles of this cscl event.
	 *
	 * @return the locales and localized titles of this cscl event
	 */
	public Map<Locale, String> getTitleMap();

	/**
	 * Sets the title of this cscl event.
	 *
	 * @param title the title of this cscl event
	 */
	public void setTitle(String title);

	/**
	 * Sets the localized title of this cscl event in the language.
	 *
	 * @param title the localized title of this cscl event
	 * @param locale the locale of the language
	 */
	public void setTitle(String title, Locale locale);

	/**
	 * Sets the localized title of this cscl event in the language, and sets the default locale.
	 *
	 * @param title the localized title of this cscl event
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setTitle(String title, Locale locale, Locale defaultLocale);

	public void setTitleCurrentLanguageId(String languageId);

	/**
	 * Sets the localized titles of this cscl event from the map of locales and localized titles.
	 *
	 * @param titleMap the locales and localized titles of this cscl event
	 */
	public void setTitleMap(Map<Locale, String> titleMap);

	/**
	 * Sets the localized titles of this cscl event from the map of locales and localized titles, and sets the default locale.
	 *
	 * @param titleMap the locales and localized titles of this cscl event
	 * @param defaultLocale the default locale
	 */
	public void setTitleMap(Map<Locale, String> titleMap, Locale defaultLocale);

	/**
	 * Returns the description of this cscl event.
	 *
	 * @return the description of this cscl event
	 */
	public String getDescription();

	/**
	 * Returns the localized description of this cscl event in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized description of this cscl event
	 */
	@AutoEscape
	public String getDescription(Locale locale);

	/**
	 * Returns the localized description of this cscl event in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this cscl event. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getDescription(Locale locale, boolean useDefault);

	/**
	 * Returns the localized description of this cscl event in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized description of this cscl event
	 */
	@AutoEscape
	public String getDescription(String languageId);

	/**
	 * Returns the localized description of this cscl event in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this cscl event
	 */
	@AutoEscape
	public String getDescription(String languageId, boolean useDefault);

	@AutoEscape
	public String getDescriptionCurrentLanguageId();

	@AutoEscape
	public String getDescriptionCurrentValue();

	/**
	 * Returns a map of the locales and localized descriptions of this cscl event.
	 *
	 * @return the locales and localized descriptions of this cscl event
	 */
	public Map<Locale, String> getDescriptionMap();

	/**
	 * Sets the description of this cscl event.
	 *
	 * @param description the description of this cscl event
	 */
	public void setDescription(String description);

	/**
	 * Sets the localized description of this cscl event in the language.
	 *
	 * @param description the localized description of this cscl event
	 * @param locale the locale of the language
	 */
	public void setDescription(String description, Locale locale);

	/**
	 * Sets the localized description of this cscl event in the language, and sets the default locale.
	 *
	 * @param description the localized description of this cscl event
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setDescription(
		String description, Locale locale, Locale defaultLocale);

	public void setDescriptionCurrentLanguageId(String languageId);

	/**
	 * Sets the localized descriptions of this cscl event from the map of locales and localized descriptions.
	 *
	 * @param descriptionMap the locales and localized descriptions of this cscl event
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap);

	/**
	 * Sets the localized descriptions of this cscl event from the map of locales and localized descriptions, and sets the default locale.
	 *
	 * @param descriptionMap the locales and localized descriptions of this cscl event
	 * @param defaultLocale the default locale
	 */
	public void setDescriptionMap(
		Map<Locale, String> descriptionMap, Locale defaultLocale);

	/**
	 * Returns the start date of this cscl event.
	 *
	 * @return the start date of this cscl event
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this cscl event.
	 *
	 * @param startDate the start date of this cscl event
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this cscl event.
	 *
	 * @return the end date of this cscl event
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this cscl event.
	 *
	 * @param endDate the end date of this cscl event
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the status of this cscl event.
	 *
	 * @return the status of this cscl event
	 */
	public int getStatus();

	/**
	 * Sets the status of this cscl event.
	 *
	 * @param status the status of this cscl event
	 */
	public void setStatus(int status);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

}