/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cscl.polls.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CsclAgeFilter service. Represents a row in the &quot;cscl_age_filter&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.cscl.polls.model.impl.CsclAgeFilterModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.cscl.polls.model.impl.CsclAgeFilterImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CsclAgeFilter
 * @generated
 */
@ProviderType
public interface CsclAgeFilterModel extends BaseModel<CsclAgeFilter> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cscl age filter model instance should use the {@link CsclAgeFilter} interface instead.
	 */

	/**
	 * Returns the primary key of this cscl age filter.
	 *
	 * @return the primary key of this cscl age filter
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cscl age filter.
	 *
	 * @param primaryKey the primary key of this cscl age filter
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_ of this cscl age filter.
	 *
	 * @return the id_ of this cscl age filter
	 */
	public long getId_();

	/**
	 * Sets the id_ of this cscl age filter.
	 *
	 * @param id_ the id_ of this cscl age filter
	 */
	public void setId_(long id_);

	/**
	 * Returns the name of this cscl age filter.
	 *
	 * @return the name of this cscl age filter
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this cscl age filter.
	 *
	 * @param name the name of this cscl age filter
	 */
	public void setName(String name);

	/**
	 * Returns the value of this cscl age filter.
	 *
	 * @return the value of this cscl age filter
	 */
	@AutoEscape
	public String getValue();

	/**
	 * Sets the value of this cscl age filter.
	 *
	 * @param value the value of this cscl age filter
	 */
	public void setValue(String value);

	/**
	 * Returns the is active of this cscl age filter.
	 *
	 * @return the is active of this cscl age filter
	 */
	public Boolean getIsActive();

	/**
	 * Sets the is active of this cscl age filter.
	 *
	 * @param isActive the is active of this cscl age filter
	 */
	public void setIsActive(Boolean isActive);

}